.catalog:
  name: "ArangoDB"
  version: "3.0-rancher1"
  description: "ArangoDB Cluster"
  uuid: arangodb-1
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
arango-dbservers:
  scale: 5
  health_check:
    port: 8529
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
arango-agency-conf:
  scale: 3
arango-coordinators:
  scale: 2
arango-dbservers-conf:
  scale: 1
arango-datavolume:
  scale: 1
arango-agency:
  scale: 3

